name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Check Style
        run: ./gradlew spotlessCheck

      - name: Run Tests
        run: ./gradlew test verifyRoborazziDebug
